# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  workflow_dispatch:

jobs:
  build:
    name: build sing-box-cvt
    runs-on: ubuntu-latest

    steps:
    - name: Set variables
      run: |
        echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
      shell: bash

    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run
      run: |
        cd sing-box-cvt/bin/Debug/net9.0
        chmod +x sing-box-cvt
        ./sing-box-cvt gfw
        ./sing-box-cvt google
        ./sing-box-cvt cn
        ls
        
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.ACTION_TOKEN }}
        release_name: Release ${{ env.BUILDTIME }}
        tag: latest
        file_glob: true
        overwrite: true
        file: ./*.conf
