# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: domain-set

on:
  workflow_dispatch:
  schedule:
  - cron: '30 23 * * *' # 8:00 AM UTC+8

jobs:
  keep-scheduled-workflow-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Keep scheduled workflow activity
        uses: WaterLemons2k/scheduled-workflow-activity-action@v1

  build:
    name: build sing-box-cvt
    runs-on: ubuntu-latest

    steps:
    - name: Set variables
      run: |
        echo "BUILDTIME=$(TZ=Asia/Shanghai date +'%Y-%m-%d %H:%M')" >> $GITHUB_ENV
      shell: bash

    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore
      
    - name: Run
      run: |
        export BIN_PATH=./sing-box-cvt/bin/Debug/net9.0/sing-box-cvt
        chmod +x $BIN_PATH
        $BIN_PATH gfw
        $BIN_PATH google
        $BIN_PATH cn
        echo --------------
        ls -l
        
    - name: Move
      run: |
        mkdir publish
        mv *.conf ./publish/
        echo --------------
        ls ./publish/
    
    - name: Release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.ACTION_TOKEN }}
        release_name: Release ${{ env.BUILDTIME }}
        tag: latest
        file_glob: true
        overwrite: true
        file: ./publish/*
